version: '2.1'

volumes:
  proxy:
  certs:
  db:
  media:
  sync-download:
  sync-staging:
  ssb-data:
services:
  # https://github.com/balenablocks/wifi-connect
  wifi:
    build: wifi
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
    environment:
      PORTAL_SSID: "P2P Hotspot"
      PORTAL_LISTENING_PORT: 8081
      APP_UI: 8081
      APP_TITLE: "Conexão de WiFi"
  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: "no"
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: p2p
  # https://hub.docker.com/r/jc21/nginx-proxy-manager/
  proxy:
    build: proxy
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - proxy:/data
      - certs:/etc/letsencrypt
    depends_on:
      - db
  # https://hub.docker.com/_/mariadb/
  db:
    image: lscr.io/linuxserver/mariadb
    restart: unless-stopped
    volumes:
      - db:/config
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Brasil
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    ports:
      - '3306:3306'
  # https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 83:80
    volumes:
      - media:/srv
    environment:
      PGID: 1000
      PUID: 1000
      APP_UI: 83
      APP_TITLE: "Navegador de Arquivos"
    command: -- c
  # TODO: ssb-pub
  ssb:
    build: ssb
    network_mode: host
    environment:
      APP_JSON: "8813:invite.json"
    volumes:
      - 'ssb-data:/root/.ssb-go'
    restart: unless-stopped
    labels:
      io.balena.features.dbus: '1'
  ipfs:
    build: ipfs
    network_mode: host
    environment:
      APP_UI: "5001/webui"
      APP_TITLE: "Syncronização de arquivos"
    volumes:
      - 'sync-download:/data/ipfs'
      - 'sync-staging:/export'
      - 'media:/data'
    labels:
      io.balena.features.supervisor-api: '1'
