version: '2.1'

volumes:
  media:
  sync-download:
  sync-staging:
  ssb-data:
services:
  # https://github.com/balenablocks/wifi-connect
  wifi-repeater:
    build: wifi-repeater
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'

  captive-portal:
    build: captive-portal
    restart: always
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: "no"
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: p2p
  # https://hub.docker.com/r/filebrowser/filebrowser
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - 83:80
    volumes:
      - media:/srv
    environment:
      PGID: 1000
      PUID: 1000
      APP_UI: 83
      APP_TITLE: "Navegador de Arquivos"
    command: -- c
  # https://hub.docker.com/repository/docker/communityfirst/ssb-go-pub
  ssb:
    image: communityfirst/ssb-go-pub:latest
    network_mode: host
    environment:
      APP_JSON: "8813:invite.json"
    volumes:
      - 'ssb-data:/root/.ssb-go'
    restart: unless-stopped
  portal:
    build: portal
    ports:
      - '80:80'
  ipfs:
    build: ipfs
    network_mode: host
    environment:
      APP_UI: "5001/webui"
      APP_TITLE: "Syncronização de arquivos"
    volumes:
      - 'sync-download:/data/ipfs'
      - 'sync-staging:/export'
      - 'media:/data'
    labels:
      io.balena.features.supervisor-api: '1'
