# cat > /root/.ssb-go/config.toml << EOF
# Where to put the log and indexes
repo = '/root/.ssb-go' 
# Where to write debug output: NOTE, this is relative to "repo" atm
debugdir = '' 

# Secret-handshake app-key (or compatible alt-key)
shscap = "1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=" 
# If set, sign with hmac hash of msg instead of plain message object using this key
hmac = "" 
# How many hops to fetch (1: friends, 2: friends of friends); note that a nodejs hops value needs to be decreased by one in go-sbot
# e.g. go-sbot hops of 1 <=> ssb-js hops of 2
hops = 1

# Address to listen on
lis = ":8008" 
# Address to listen on for ssb websocket connections
wslis = ":8989"
# Address to listen on for metrics and pprof HTTP server
debuglis = "localhost:6078" 

# Enable sending local UDP broadcasts
localadv = true 
# Enable connecting to incoming UDP broadcasts
localdiscov = true 
# Enable syncing by using epidemic-broadcast-trees (EBT)
enable-ebt = true 
# Bypass graph auth and fetch remote's feed, useful for pubs that are restoring their data from peers. Caveats abound, however.
promisc = true 
# Disable the UNIX socket RPC interface
nounixsock = false
repair = true
# EOF