FROM  ipfs/go-ipfs:master-latest

# COPY config /data/ipfs/

# TODO add mdns?
# RUN install_packages dbus systemd avahi-daemon libnss-mdns

# RUN systemctl mask \
#     dev-hugepages.mount \
#     sys-fs-fuse-connections.mount \
#     sys-kernel-config.mount \
#     display-manager.service \
#     getty@.service \
#     systemd-logind.service \
#     systemd-remount-fs.service \
#     getty.target \
#     graphical.target

# STOPSIGNAL 37

# CMD ["bash", "start.sh"]
