# Build stage
FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

RUN apt update -y && apt install -y wget unzip apache2

WORKDIR /var/run/apache2
# apache
COPY apache-config/* /etc/apache2/

COPY start.sh .
CMD ["bash", "start.sh"]
